name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: my-artifact
    path: build/


      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
